services:
  go-service:
    build:
      context: ./go
      dockerfile: build/Dockerfile
    volumes:
      - temp-audio:/temp-audio
    networks:
      - ai-detector-network
    environment:
      BOT_TOKEN: "7294621562:AAE9AG13GiZFms57CvV6fDMhwqb8LYMzsv8"
    depends_on:
      - fastapi

  fastapi:
    build:
      context: ./python
      dockerfile: build/Dockerfile
    volumes:
      - temp-audio:/temp-audio
    networks:
      - ai-detector-network
  #  ports:
  #    - "8090:8090"

networks:
  ai-detector-network:
    driver: bridge

volumes:
  temp-audio: