services:
  go-service:
    build:
      context: ./go
      dockerfile: build/Dockerfile
    volumes:
      - temp-audio:/app/temp-audio
    networks:
      - ai-detector-network
    environment:
      - BOT_TOKEN=
    depends_on:
      - python-service

  python-service:
    build:
      context: ./python
      dockerfile: build/Dockerfile
    volumes:
      - temp-audio:/app/temp-audio
    networks:
      - ai-detector-network
    ports:
      - "8090:8090"

networks:
  ai-detector-network:
    driver: bridge

volumes:
  temp-audio: