services:
  go-service:
    build:
      context: ./go
      dockerfile: build/Dockerfile
    volumes:
      - temp-audio:/temp-audio
    networks:
      - ai-detector-network
    environment:
      BOT_TOKEN: "" #Добавить токен
    depends_on:
      - fastapi
    #restart: always             #Автозапуск для развертывания на сервере

  fastapi:
    build:
      context: ./python
      dockerfile: build/Dockerfile
    volumes:
      - temp-audio:/temp-audio
    networks:
      - ai-detector-network
    #restart: always            #Автозапуск для развертывания на сервере

networks:
  ai-detector-network:
    driver: bridge

volumes:
  temp-audio:
